### PR TITLE
Historical section

### PR DESCRIPTION
**Pull request by khubaibshah786**
- Updated the Paid conversion card header with bootstrap colour warning
- Updated Paid conversion card input field arrangement
- Updated the Exchange amount field to show a Reset button to clear out previous input
- Updated Exchange amount field to show bootstrap dollar icon
- Updated currency fields to show labels as base currency and target currency
- Updated convert image to bootstrap currency icon
- Updated the conversion rate card header with bootstrap background colour of success or danger
- Updated Conversion rate card with error text when '0' or no number in exchange amount field
- Created Historical Conversion card to show historic currency data
- Added selection field with currencies to select from
- Added a Date input field to allow user to select date
- Added Convert button
- Added information about which currencies can be selected from which dates
- Added section in Historical card to show historic currency data in a table generated by jQuery
- Added Bootstrap icons to card headers
- Added comments in the script,js file to explain all the logic
- Updated the HTML file to reflect the changes

### CODE REVIEW

**Review by dpaul93 — APPROVED** [review]
big fan. Great work mate. Looking through previous merges the application has developed a lot. Happy for this to be pushed into main. Not necessary for now but for go live we can look to delete the unnecessary comments.

**Review by jcesarmarcondes — APPROVED** [review]
Brilliant work mate, well done!

**Review by CNtervisi — APPROVED** [review]
Nice! Great work mate.

**Comment by Yaroslav09** [comment]
Great work. Thanks

**Review by Yaroslav09 — APPROVED** [review]

**Pull request merged**
